- name: Ansible Jenkins Playbook
  remote_user: godi
  become: yes
  hosts: TEST
  tasks:
    - name: Install Java
      command: apt install -y default-jre
    - name: Download Artifact
      get_url:
        url: http://34.93.60.168:8081/service/rest/v1/search/assets/download?sort=version&direction=desc&maven.groupId=com.maven.test&maven.artifactId=jenkins_test&maven.extension=jar
        dest: /opt/simple-java-app.jar
